services:
  app-prod:
    image: ${PROD_IMAGE_NAME}
    container_name: ${PROD_CONTAINER_NAME}

    build:
      context: .
      dockerfile: packages/apps/web/Dockerfile.prod
      args:
        NODE_VERSION: ${NODE_VERSION}
        DISTROLESS_NODE_IMAGE: ${DISTROLESS_NODE_IMAGE}
        APP_PORT: ${APP_PORT}

    restart: unless-stopped

    ports:
      - "${HOST_PORT_PROD}:${APP_PORT}"

    depends_on:
      app-service-prod:
        condition: service_healthy

    environment:
      NODE_ENV: ${NODE_ENV_PROD}
      HOSTNAME: ${APP_HOSTNAME}
      PORT: ${APP_PORT}

    command:
      - node_modules/next/dist/bin/next
      - start
      - packages/apps/web
      - -H
      - ${APP_HOSTNAME}
      - -p
      - "${APP_PORT}"

  app-service-prod:
    build:
      context: .
      dockerfile: packages/apps/service/Dockerfile.prod
      args:
        NODE_VERSION: ${NODE_VERSION}
        DIRSTROLESS_NODE_IMAGE: ${DISTROLESS_NODE_IMAGE}
    ports:
      - "8088:3000"
    environment:
      NODE_ENV: production
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
